---
all:
  children:
      staging-checkmarx:
        hosts:
          cxm-agt-[001:010]-s.cisco.com:
      production-checkmarx:
        hosts:
          cxm-agt-[001:045]-p.cisco.com:
          cxm-ctr-[001:003]-p.cisco.com:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_credssp_disable_tlsv1_2: true